// vue3/vue3_test/18_src_Teleport_闪送/components/child.vue
<!--
 * @Author: liwz
 * @Date: 2025-01-22 15:12:57
 * @LastEditors: liwz
 * @LastEditTime: 2025-02-24 10:52:23
 * @FilePath: /study_new/vue3/vue3_test/src/components/child.vue
 * @Description:
 *
 * Copyright (c) 2025 by ${git_name_email}, All Rights Reserved.
-->
<template>
  <div class="child">
    我是Child组件

    <Son />
  </div>
</template>

<script>
import { toRefs, reactive, inject } from 'vue'

import Son from './son.vue'
export default {
  components: { Son },
  name: 'Child'
}
</script>

<style>
.child {
  background: skyblue;
  padding: 10px;
}
</style>

// react-staging/src/components/9_getDerivedStateFromError/child.jsx
/*
 * @Author: liwz
 * @Date: 2025-02-27 13:46:29
 * @LastEditors: liwz
 * @LastEditTime: 2025-02-27 14:09:40
 * @FilePath: /study_new/react-staging/src/components/9_getDerivedStateFromError/child.jsx
 * @Description:
 *
 * Copyright (c) 2025 by ${git_name_email}, All Rights Reserved.
 */
import React, { Component } from 'react'

export default class Child extends Component {
  state = {
    /* stus: [
      { id: '001', name: '张三', age: 18 },
      { id: '002', name: '李四', age: 19 },
      { id: '003', name: '王五', age: 20 }
    ] */
    stus: 'abc'
  }

  render() {
    return (
      <div>
        <ul>
          {this.state.stus.map(item => {
            return (
              <li key={item.id}>
                {item.name}-----{item.age}
              </li>
            )
          })}
        </ul>
      </div>
    )
  }
}
